---
title: "office_hours_activity"
format: html
editor: visual
editor_options: 
  chunk_output_type: console
---

```{r}
library(tidyverse)
```


```{r}
precip_in<-runif(1e4,min=10,max=100)
hist(precip_in)
```

```{r}
beta0<-8
beta1<-0.75
sigma<-3
u<-rnorm(1e4,mean=0,sd=sigma)
tree_height<-beta0+beta1*precip_in + u

tree_pop<-tibble(precip_in, tree_height)
ggplot(tree_pop,aes(precip_in, tree_height))+ geom_point(alpha=0.05)+
  geom_abline(slope=beta1,
              intercept=beta0,
              color="firebrick",
              linewidth=2)

pop_lm<-lm(tree_height ~ precip_in, tree_pop)
summary(pop_lm)

tree_sample<- sample_n(tree_pop,10)

tree_pop<-tibble(precip_in, tree_height)

ggplot(tree_pop,aes(precip_in, tree_height))+ 
  geom_point(alpha=0.05)+
  geom_abline(slope=beta1,
              intercept=beta0,
              color="firebrick",
              linewidth=2)+ 
  geom_point(data=tree_sample,
           color="cornflowerblue")

sample_lm<-lm(tree_height ~precip_in, tree_sample)
summary(sample_lm)

ggplot(tree_pop,aes(precip_in, tree_height))+ 
  geom_point(alpha=0.05)+
  geom_abline(slope=beta1,
              intercept=beta0,
              color="firebrick",
              linewidth=2)+ 
  geom_point(data=tree_sample,
           color="cornflowerblue") +
  geom_abline(slope=0.7653,
              intercept=7.69342,
              color="cornflowerblue",
              linewidth=1.5)

summary(sample_lm)$coeff["precip_in", "Estimate"]

```

